import type { Metadata } from "next";
import React, { Suspense } from "react";
import "./globals.css";
import Navbar from "./components/shared/Navbar/Navbar";
import localFont from "next/font/local";

import SmoothScroll from "./components/Functions/SmoothScroller";
import Noise from "./components/Functions/Noise";
import Grain from "./components/Functions/Grain";
import Footer from "./components/shared/Footer/Footer";
import CookieBanner from "./components/shared/cookie-banner";
import GoogleAnalytics from "./components/shared/google-analytics";
import { Analytics } from "@vercel/analytics/react";

const Humane = localFont({
  src: [
    {
      path: "fonts/Humane-Black.woff2",
      weight: "900",
      style: "normal",
    },
    {
      path: "fonts/Humane-Bold.woff2",
      weight: "700",
      style: "normal",
    },
    {
      path: "fonts/Humane-Medium.woff2",
      weight: "500",
      style: "normal",
    },
    {
      path: "fonts/Humane-Regular.woff2",
      weight: "400",
      style: "normal",
    },
    {
      path: "fonts/Humane-Light.woff2",
      weight: "300",
      style: "normal",
    },
  ],
  variable: "--font-Humane",
});

export const metadata: Metadata = {
  title: "Jannis Röstel | Web- und Motiondesigner aus Karlsruhe",
  description: "Generated by create next app",
};
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html className={`${Humane.variable} `} lang="de">
      <Suspense fallback={null}>
        <GoogleAnalytics GA_MEASUREMENT_ID="G-T3JQ8R8YRC" />
      </Suspense>
      <SmoothScroll />

      <body className="bg-darkBlue-500 text-white scroll-smooth">
        <CookieBanner />
        <Analytics />
        <Noise />
        <Grain />
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
